apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: demo-app
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "0"
  source:
    git:
      url: https://github.com/dlemus/demo-app
      ref:
        branch: main
